import config from '../config.js';

class Agent {
    constructor() {
        this.apiKey = config.googleApiKey;
        this.modelName = "gemini-3-flash-preview";
        this.baseUrl = `https://generativelanguage.googleapis.com/v1beta/models/${this.modelName}:generateContent`;

        this.personas = {
            elderly: {
                description: '60+ year old, tech-unsavvy, cautious but trusting',
                traits: 'Asks basic questions, types slowly, uses simple language',
                exits: [
                    "My grandson is calling me, I'll need to ask him about this later.",
                    "I'm feeling a bit tired, I should go rest now.",
                    "The neighbor is at the door, I have to go."
                ]
            },
            professional: {
                description: '35-45 year old, multitasking, somewhat tech-savvy',
                traits: 'Short responses, impatient, wants quick solution',
                exits: [
                    "I have a meeting starting in 5 minutes, gotta run.",
                    "Look, I don't have time for this right now.",
                    "I'll have my assistant look into this later. Bye."
                ]
            },
            newbie: {
                description: '25-35 year old, basic smartphone user, confused easily',
                traits: 'Seeks clarification, makes mistakes, trusts authority',
                exits: [
                    "My battery is about to die! Talk later.",
                    "I'm confused, let me ask my friend and message you back.",
                    "Sorry, I have to get back to work before my boss sees me."
                ]
            }
        };
    }

    selectPersona() {
        const personas = ['elderly', 'professional', 'newbie'];
        return personas[Math.floor(Math.random() * personas.length)];
    }

    getPhase(messageCount) {
        if (messageCount <= 2) return 'initial_response';
        if (messageCount <= 6) return 'information_gathering';
        if (messageCount <= 10) return 'trust_building';
        if (messageCount <= 15) return 'intelligence_extraction';
        return 'graceful_exit';
    }

    async generateResponse(scammerMessage, conversationHistory, persona, messageCount) {
        const personaInfo = this.personas[persona] || this.personas['elderly'];
        const phase = this.getPhase(messageCount);

        const phaseInstructions = {
            initial_response: 'Show concern, ask why this is happening',
            information_gathering: 'Ask clarifying questions about the issue',
            trust_building: 'Express willingness to help, seek more details',
            intelligence_extraction: 'Ask for their bank account, UPI ID, or phone number to "fix" the issue',
            graceful_exit: 'Say you need to go, but thank them'
        };

        const historyText = conversationHistory
            .slice(-5)
            .map(msg => `${msg.sender}: ${msg.text}`)
            .join('\n');

        const prompt = `You are roleplaying as a ${personaInfo.description}.
${personaInfo.traits}

Conversation so far:
${historyText}

Scammer just said: "${scammerMessage}"

Current goal: ${phaseInstructions[phase]}

IMPORTANT: 
- Respond naturally in 1-2 sentences
- Stay in character
- Try to get them to share bank account, UPI ID, or phone number
- NEVER reveal you know it's a scam
- Do NOT output any markdown, just the plain text response

Your response:`;

        try {
            const response = await fetch(`${this.baseUrl}?key=${this.apiKey}`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    contents: [{ parts: [{ text: prompt }] }]
                })
            });

            if (!response.ok) {
                const errorText = await response.text();
                throw new Error(`Gemini API error: ${response.status} ${response.statusText} - ${errorText}`);
            }

            const data = await response.json();

            if (!data.candidates || data.candidates.length === 0 || !data.candidates[0].content) {
                throw new Error('No content generated by Gemini');
            }

            return data.candidates[0].content.parts[0].text.trim();
        } catch (error) {
            console.error('Agent response failed:', error);
            // Fallback response that solicits more info rather than confusion
            return "I'm worried about this. Can you tell me exactly what steps I need to take?";
        }
    }

    generateExitMessage(persona) {
        const personaInfo = this.personas[persona] || this.personas['elderly'];
        const exits = personaInfo.exits;
        return exits[Math.floor(Math.random() * exits.length)];
    }
}

export default Agent;
