import config from '../config.js';

class ScamDetector {
    constructor() {
        this.apiKey = config.googleApiKey;
        this.modelName = "gemini-3-flash-preview";
        this.baseUrl = `https://generativelanguage.googleapis.com/v1beta/models/${this.modelName}:generateContent`;

        this.scamKeywords = [
            'blocked', 'verify', 'urgent', 'immediately',
            'kyc', 'tax refund', 'prize', 'lottery', 'won',
            'suspended', 'click here', 'confirm', 'otp', 'cvv',
            'account', 'bank', 'payment', 'expire', 'warning'
        ];
    }

    // Quick keyword check
    checkKeywords(message) {
        const lowerMsg = message.toLowerCase();
        const matches = this.scamKeywords.filter(kw => lowerMsg.includes(kw));
        return {
            score: matches.length > 0 ? matches.length / this.scamKeywords.length : 0,
            matchedKeywords: matches
        };
    }

    // Use Gemini to analyze
    async analyzeWithGemini(message) {
        const prompt = `Analyze this message for scam patterns: "${message}"

Respond with JSON only (no markdown):
{
  "is_scam": true or false,
  "confidence": 0.0 to 1.0,
  "scam_type": "bank_fraud" or "phishing" or "lottery_scam" or "tech_support" or "unknown",
  "reasoning": "brief explanation"
}`;

        try {
            const response = await fetch(`${this.baseUrl}?key=${this.apiKey}`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    contents: [{ parts: [{ text: prompt }] }],
                    generationConfig: { responseMimeType: "application/json" }
                })
            });

            if (!response.ok) {
                const errorText = await response.text();
                throw new Error(`Gemini API error: ${response.status} ${response.statusText} - ${errorText}`);
            }

            const data = await response.json();

            // Validation
            if (!data.candidates || data.candidates.length === 0 || !data.candidates[0].content) {
                throw new Error('No content generated by Gemini');
            }

            const text = data.candidates[0].content.parts[0].text;
            console.log('Gemini raw response:', text);

            // Parse JSON (remove markdown if present)
            const cleanText = text.replace(/```json\n?|\n?```/g, '').trim();
            return JSON.parse(cleanText);
        } catch (error) {
            console.error('Gemini analysis failed:', error);
            return {
                is_scam: true, // Default to scam on error for safety
                confidence: 0.5,
                scam_type: 'unknown',
                reasoning: `Analysis failed: ${error.message}`
            };
        }
    }

    async detect(message) {
        // Layer 1: Keywords
        const keywordResult = this.checkKeywords(message);

        // Always use Gemini for analysis (remove threshold limitation)
        const geminiResult = await this.analyzeWithGemini(message);

        return {
            isScam: geminiResult.is_scam,
            confidence: geminiResult.confidence,
            scamType: geminiResult.scam_type,
            reasoning: geminiResult.reasoning,
            keywordMatches: keywordResult.matchedKeywords,
            keywordScore: keywordResult.score
        };
    }
}

export default ScamDetector;

